Hack

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -33,6 +33,6 @@ jobs:
             echo "EC2 host - $EC2_HOST"
             chmod 755 chef_commands.sh
             while ! ssh -o StrictHostKeyChecking=no ubuntu@$EC2_HOST; do \
-            echo "SSH failed, retrying..." >&2; done
+            echo "SSH failed, retrying..." >&2 && sleep 5; done
             scp -o StrictHostKeyChecking=no rds_endpoint.txt chef_commands.sh ubuntu@$EC2_HOST:~
             ssh -o StrictHostKeyChecking=no ubuntu@$EC2_HOST './chef_commands.sh'
