Fixes

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -23,8 +23,7 @@ jobs:
           command: |
             export EC2_NAME=$(sed -n 's/ec2_instance_name.*\(".*"\)/\1/p' terraform.tfvars | tr -d '"')
             export REGION=$(sed -n 's/region.*\(".*"\)/\1/p' terraform.tfvars | tr -d '"')
-            chmod 755 .circleci/circleci_init.sh
-            ./.circleci/circleci_init.sh
+            chmod 755 .circleci/circleci_init.sh && ./.circleci/circleci_init.sh
       - run:
           name: Terraform Deployment
           command: |
@@ -36,16 +35,12 @@ jobs:
       - run:
           name: Chef Deployment
           command: |      
-            echo $EC2_HOST
-            # EC2_HOST="$(cat ec2_endpoint.txt)"
-            # echo "Wait for 2 minutes until Chef is configured on the instance" && sleep 120
-            # while ! scp -o StrictHostKeyChecking=no *endpoint.txt chef_commands.sh $USER@$EC2_HOST:/tmp; do echo "SSH failed, retrying..."; sleep 5; done;
-            # ssh -o StrictHostKeyChecking=no $USER@$EC2_HOST 'cd /tmp; chmod 755 chef_commands.sh && ./chef_commands.sh'
+            echo "Wait for 2 minutes until Chef is configured on the instance" && sleep 120
+            while ! scp -o StrictHostKeyChecking=no *endpoint.txt chef_commands.sh $USER@$EC2_HOST:/tmp; do echo "SSH failed, retrying..."; sleep 5; done;
+            ssh -o StrictHostKeyChecking=no $USER@$EC2_HOST 'cd /tmp; chmod 755 chef_commands.sh && ./chef_commands.sh'
       - run:
           name: Check if WP application is available
           command: |
-            echo $EC2_HOST
-            # EC2_HOST="$(cat ec2_endpoint.txt)"
-            # until $(curl -sS http://$EC2_HOST > /dev/null); do sleep 5; done
+            until $(curl -sS http://$EC2_HOST > /dev/null); do sleep 5; done
 
 # scp -o StrictHostKeyChecking=no rds_endpoint.txt chef_commands.sh ubuntu@$EC2_HOST:~
