Fix

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -32,7 +32,7 @@ jobs:
             EC2_HOST="$(terraform output ec2_endpoint)"
             echo "EC2 host - $EC2_HOST"
             echo "Wait for 2 minutes until Chef is configured on the instance" && sleep 120
-            while ! scp -o StrictHostKeyChecking=no rds_endpoint.txt chef_commands.sh ubuntu@$EC2_HOST:~; do echo "SCP failed, retrying..." && sleep 5; done;
+            while ! scp -o StrictHostKeyChecking=no rds_endpoint.txt chef_commands.sh ubuntu@$EC2_HOST:~; do echo "SSH failed, retrying..." && sleep 5; done;
             ssh -o StrictHostKeyChecking=no ubuntu@$EC2_HOST 'chmod 755 chef_commands.sh && ./chef_commands.sh'
 
 # scp -o StrictHostKeyChecking=no rds_endpoint.txt chef_commands.sh ubuntu@$EC2_HOST:~
